name: small-pipeline

on: push


jobs:
  build:

  runs-on: ubuntu-24.04

  steps:

  - name: Checkout
  uses: actions/checkout@v3



  -name: Setup Node.js
  uses: actions/setup-node@v3
  with:
    node-version: '22.6.0'


  -name: Install dependencies
   run: npm install jest


  -name: Run tests
   run: test
